### DISCUSSION TITLE
Is there a ms365_calendar.next_free_slot_calendar_event or something similar?

### DISCUSSION THREAD

**Discussion by fft1010** [RogerSelwyn/O365-HomeAssistant#264] [Q&A]
Hi,
I hope I am right here. I am trying to book the next free 15 minute Slot in a calendar. I managed to book a free slot in a room (where I check manually before, if it is free) in a HA script:

```
action: o365.create_calendar_event
metadata: {}
data:
  subject: Framery booking
  start: 2024-12-10T13:00:00+0100
  end: 2024-12-10T13:15:00+0100
target:
  entity_id: calendar.kalender_framery_test
```

I just wonder, if I need to program "find the next free slot" on my own, or if this might be already somewhere implemented? I did not find anything. Many thanks in advance

all the best
Juergen
