### ISSUE TITLE
Check Configuration won't finish after adding O365-HomeAssistant

### ISSUE THREAD

**Issue by MasterDevwi** [RogerSelwyn/O365-HomeAssistant#110]
Hello,

I'm excited to use this integration. Unfortunately, after I added the configuration to configuration.yaml, the Home Assistant Configuration Check in Developer Tools enters an endless loop and never finishes checking the YAML. Since I can't see if it succeeds or fails, I'm worried about proceeding with a restart to finish setup.

I've tried using both the primary and secondary configuration formats, as well as varying the number of accounts and even stripping out everything except the account_name, client_id, and client_secret. Nothing seems to prevent the endless loop in the config check. But if I remove the "o365" config from config.yaml and then refresh it instantly succeeds.

o365:
  accounts:
    - account_name: personal
      client_id: "redacted"
      client_secret: "redacted"
    - account_name: work
      client_id: "redacted"
      client_secret: "redacted"

(I can't get the indentation to appear correctly in this post, but it matches the documentation exactly.)

Is this a known issue? Any suggestions for how to fix it?

Thanks in advance for your help!

**Comment by RogerSelwyn** [comment]
Please use the `Add code` (`<>`)tool to properly format anything you post. I assume it looks like this:

```
o365:
  accounts:
    - account_name: personal
      client_id: "redacted"
      client_secret: "redacted"
    - account_name: work
      client_id: "redacted"
      client_secret: "redacted"
```
I wouldn't ever expect your config checker to loop. I would remove the config, then restart (because you need to have done that before adding the config anyway). Beyond that I really don't know. I'd suspect it is something to do with your setup, but of course you never know.... But with approx 2k users out there, it hasn't come up before.
