### ISSUE TITLE
ToDo: Track status of task created by o365 integration

### ISSUE THREAD

**Issue by wigster** [RogerSelwyn/O365-HomeAssistant#112]
Hi,

My use-case is possibly the opposite to the typical: I want to make HA create tasks, to get me to do maintenance on the house (e.g. a battery is low and needs to be changed, or the washing machine needs to have a drum clean cycle run). I can easily do this with your integration -- so thanks!

But I would like to be able to track the status of the particular task that HA created. So e.g. if HA creates a task to clean the drum, it will keep running some automation until I complete it in the phone ToDO application.

Is there some task ID that I can retrieve at the time of setting the task by HA, whose completion I could check in an automation? Or some other way of doing this?

**Comment by RogerSelwyn** [comment]
Sorry, I really thought I had replied to this when you posted.

From a service call (which is what you are doing however you initiate a create task), there is no return value mechanism via the HA core. So whilst the task_id is provided in the task list against the sensor entity, you would need to be able to identify which task in the list is the one you created. I could add the created date/time against the task in the list if that would help.

**Comment by B-Hartley** [comment]
Yes, I'd be looking for this use case too.
Only just starting playing with this.
maybe an event could be fired when the task is created and the automation that created it, could wait for that event and capture the ID.
Probably overkill and there is probably a simpler way, like grab the most recent task? or check the subject of the task and store the ID or something like that. 

Will have an experiment and see how I get on.

I had to create a MPN ID to be eable to use the authentication.  Not sure if that is normal, but it seemed to be required.

**Comment by RogerSelwyn** [comment]
I'm going to look at event firing based on your other request, if I can get that going, I'm sure I can fire an event with the task-I'd at create time

**Comment by B-Hartley** [comment]
Fab.

**Comment by RogerSelwyn** [comment]
You'll get an event like this:

```yaml
event_type: o365_new_task
data:
  task_id: >-
    AAMkAGQwYzQ5ZjZjLTQyYmItNDJmNy04NDNjLTJjYWY3NzMyMDBmYwBGAAAAAAC9VxHxYFTdSrdCHSJkXtJ-BwCoiRErLbiNRJDCFyMjq4khAAbWN3xqAACoiRErLbiNRJDCFyMjq4khAAcYapadAAA=
origin: LOCAL
time_fired: "2023-02-18T11:35:56.809987+00:00"
context:
  id: 01GSJ4YC495W73HW1PQQ1HM5W9
  parent_id: null
  user_id: null
```
