### ISSUE TITLE
Calendar error 

### ISSUE THREAD

**Issue by The-Darjeeling** [RogerSelwyn/O365-HomeAssistant#114]
updated to 4.1.0 from the last release, now i get an error for duplicate Id's in calendar. Is there a change to how calendars were handled, previously i had a set of entites under a single cal_ID using searches for different events. I've checked the syntax and it seems match whats on the documentation & have deleted the copied over o365_calendar.yaml from the migration in case that was causing it

```
cal_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  entities:
    
  - device_id: Calendar
    end_offset: 24
    name: Calendar
    start_offset: 0
    track: true

  - device_id: Tesco
    end_offset: 24
    name: Tesco
    start_offset: 0
    search: "Tesco order due"
    track: true
```
