### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by mplogas** [RogerSelwyn/O365-HomeAssistant#12]
**system:**
Home Assistant version: 2021.12.8
Plugin version: 2.2.7
AAD SKU: AAD P1
AAD app registration: single tenant, no MSA
(M365 is requiring MFA on all accounts)

**plugin config:**
```yaml
o365:
  client_secret: !secret o365_clientsecret
  client_id: !secret o365_appid
  email_sensor:
    - name: inbox
      max_items: 2
      is_unread: True
  query_sensors:
    - name: "HA Notifications"
      folder: "Inbox/Test_Inbox"
      from: "mail@example.com"
      subject_contains: "Notifcation from home assistant"
      has_attachment: True
      max_items: 2
      is_unread: True
```

**AAD app config:**
![image](https://user-images.githubusercontent.com/842121/148792813-70105fd5-a944-4e12-9f4b-0f064b2897ca.png)

**expected behaviour:** 
1. when clicking "Link O365 account" I am forwarded to my orgs login page
2. entering credentials and receiving MFA request
3. (surprisingly no consent screen is being shown)
4. login page closes 
5. Pressing "I authorized successfully" should have received and stored the token

observed behaviour:
the return-url does not seem to receive (or being able to parse) the token. When calling the return uri directly (https://<myid>.ui.nabu.casa/api/o365) I receive a ```Error, the originating url does not seem to be a valid microsoft redirect``` so I assume the return_uri endpoint is available.

HA logs:
```
This error originated from a custom integration.

Logger: custom_components.o365.utils
Source: custom_components/o365/utils.py:45
Integration: Office 365 Calendar (documentation, issues)
First occurred: 3:58:15 PM (2 occurrences)
Last logged: 3:58:15 PM

Could not loacte token at .O365-token-cache/o365.token
```
