### ISSUE TITLE
Not showing calendar sensors

### ISSUE THREAD

**Issue by helmerzNL** [RogerSelwyn/O365-HomeAssistant#121]
I have the integration installed and I do see almost all sensors (mail and tasks are working just fine),  but the calendar is not showing up. In the logfile I do see an authentication error. I removed the token an authorized again (and rebooted HA afterwards), but that does not solve the problem.

o365_calendars_helmer.yaml
```
- cal_id: AQMkADBlZmQyOD***********************************************************tM0AAAIY-wAAAA==
  entities:
  - device_id: Agenda
    end_offset: 168
    name: Agenda Helmer
    start_offset: 0
    track: true

- cal_id: AAMkADBlZmQyODA3LWE3ZTQtND*****************************************************************AAAAAEGAAAwYE7_CwBkQ4ChJvuucLTNAAR0IuRGAAA=
  entities:
  - device_id: Familie Zandbergen
    end_offset: 168
    name: Familie Zandbergen
    start_offset: 0
    track: true
```

microsoft_o365_integration.yaml
```
o365:
  accounts:
    - account_name: M365-Helmer
      client_id: !secret m365_client_id
      client_secret: !secret m365_client_secret
      alt_auth_method: False
      enable_update: True
      email_sensor:
        - name: Inbox Helmer
          max_items: 2
          is_unread: True
          download_attachments: False
      query_sensors:
        - name: "MSMail"
          folder: "Inbox" #Default is Inbox
          from: "helmerz@microsoft.com"
          subject_contains: "[HA]"
          has_attachment: false
          max_items: 4
          is_unread: True
        - name: "Regina"
          folder: "Inbox" #Default is Inbox
          from: "regina@zandbergenonline.nl"
          subject_contains: ""
          has_attachment: false
          max_items: 4
          is_unread: True          
      status_sensors: # Cannot be used for personal accounts
        - name: "Helmer Teams Status"
      chat_sensors: # Cannot be used for personal accounts
        - name: "Helmer Chat"
      todo_sensors:
        enabled: true
      groups: false
      track_new_calendar: true
```

And the error I see in the logfile

Logger: O365.connection
Source: /usr/local/lib/python3.10/site-packages/O365/connection.py:793
First occurred: 18:12:52 (2 occurrences)
Last logged: 18:12:52

Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/calendars/AA**********************************************adbYGQJbBtpJeR9ZxBwAwYE7_CwBkQ4ChJvuucLTNAAR0IuRGAAA=/calendarView?%24top=999&startDateTime=2023-02-08T23%3A00%3A00%2B00%3A00&endDateTime=2023-02-09T23%3A00%3A00%2B00%3A00 | Error Message: Access is denied. Check credentials and try again.
Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/calendars/AQMkADB*************************************************0AAAIY-wAAAA==/calendarView?%24top=999&startDateTime=2023-02-08T23%3A00%3A00%2B00%3A00&endDateTime=2023-02-09T23%3A00%3A00%2B00%3A00 | Error Message: Access is denied. Check credentials and try again.

I masked the ID's in the URL's and calendar ID's myself.
