### ISSUE TITLE
Minimum permissions not granted for account - All API permissions granted and No "Status" & "Chat" sensor

### ISSUE THREAD

**Issue by alfonslm** [RogerSelwyn/O365-HomeAssistant#155]
![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/10770782/d57b4921-627d-47d8-922d-4f08e50bd5db)
I have really tired to follow the documentation to resolve the "Minimum permissions not granted for account" error but can't figure out how to get it to work.
When I check the log the only help it gives is this lines
`2023-08-16 13:43:47.926 WARNING (MainThread) [custom_components.o365.utils.permissions] Could not locate token at /config/o365_storage/.O365-token-cache/o365_Account1.token`
`2023-08-16 13:32:10.552 WARNING (MainThread) [custom_components.o365] No token, or token doesn't have all required permissions; requesting authorization for account: Account1`

```
o365:
  accounts:
    - account_name: Account1 # Do not use email address or spaces
      client_id: "xxxxxxxx-ff85-437e-8cb1-f28bcda9e8c6"
      client_secret: "xxxxxxxx-370b-4d0a-8efb-787dc49de00f"
      alt_auth_method: False
      enable_update: True
      email_sensor:
        - name: inbox
          max_items: 2
          is_unread: True
          download_attachments: False
      query_sensors:
        - name: "Example"
          folder: "Inbox/Test_Inbox" #Default is Inbox
          from: "mail@example.com"
          subject_contains: "Example subject"
          has_attachment: True
          max_items: 2
          is_unread: True
      todo_sensors:
        enabled: True
```

![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/10770782/92ac5388-bec8-465c-9959-e804b61020f2)

**Comment by RogerSelwyn** [comment]
It sounds like you have deleted the token, it is asking you authenticate. There should be a repair showing in HA, which you need to complete.

May guess is that you are using a personal account, for which Teams sensors are not supported. Please see text below from the Errors page of the documentation.

No token, or token doesn’t have all required permissions; requesting authorization for account: Account1 Minimum required permissions not granted: [‘Presence.Read’, []]
- Where this error mentions Presence.Read or Chat.Read it probably means you have tried to configure a Teams Presence or Chat sensor when your account is a Personal Account (such as @outlook.com)
- For other items, it means you have changed your configuration to require new permissions. You will likely need to delete your token and reauthenticate. Please check the [permissions page](https://rogerselwyn.github.io/O365-HomeAssistant/permissions.html) for more details.

Please re-authenticate and then post whatever error you get at that stage.

**Comment by alfonslm** [comment]
![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/10770782/93b7725d-947e-47a6-928d-2a0a8736836c)
From what I can se that file wouldn't exist yet

**Comment by RogerSelwyn** [comment]
Have you tried authenticating?

**Comment by alfonslm** [comment]
Yes. The error is after I have signed in and copied the link

**Comment by RogerSelwyn** [comment]
I would suggest deleting the app and recreating, then starting with just the calendar to make sure you have the basics working.

If that doesn't work I will test with your posted config tomorrow and see if I can understand what is going on.

**Comment by alfonslm** [comment]
Nop. Got the same error with this configuration.
```
o365:
  accounts:
    - account_name: Account1 # Do not use email address or spaces
      client_id: "xxxxxxxx-ff85-437e-8cb1-f28bcda9e8c6"
      client_secret: "xxxxxxxx-370b-4d0a-8efb-787dc49de00f"
      alt_auth_method: False
      enable_update: True
```

**Comment by alfonslm** [comment]
Same with this config
```
o365:
  accounts:
    - account_name: Account1 # Do not use email address or spaces
      client_id: "xxxxxxxx-ff85-437e-8cb1-f28bcda9e8c6"
      client_secret: "xxxxxxxx-370b-4d0a-8efb-787dc49de00f"
      alt_auth_method: False
      enable_update: False
```
