### ISSUE TITLE
Agenda appointments seem to be mixed up between two different accounts. 

### ISSUE THREAD

**Issue by Zaleo80** [RogerSelwyn/O365-HomeAssistant#156]
Could not find any similar issue here, hope I did not overlook something.

### The issue
I tweaked around with Azure AD to integrate the calendars in home assistant before all seemed to work.
There is only one caviar, both calendars from two different Office 365 subscriptions contain the appointments of the one I configured first (Not sure if this is coincidence or related).

When I click on the Kalender in the menu I see purple and blue agenda's, both containing the same appointments.
The blue one should contain my work appointments the purple one my private appointments.

![DubbelApointments](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/128542757/6723a1f2-40fa-4684-8441-390aa59bdeec)

### Configuration

1. Installed using HACS
2. Configured both accounts in configuration
3. Did notice the two calendars had the same device_id's in there o365_Calander_{account}.yaml files
4. Changed the device_id's (and names) to be unique

configuration.yaml:
```
o365:
  accounts:
    - account_name: Prive # Do not use email address or spaces
      client_id: "5bd0xxx9-66f8-3548-xw8x-1564864xxxxxx77"
      client_secret: !SECRETPRIVATEAPP
      alt_auth_method: False
      enable_update: True
      email_sensor:
        - name: Office 365 Prive Inbox
          max_items: 2
          is_unread: True
          download_attachments: False
      status_sensors: # Cannot be used for personal accounts
        - name: "Office 365 Prive State"
      todo_sensors:
        enabled: False
    - account_name: Work
      client_id: "xx046xxx-91ca-4x52-8xx4-5xxxxxxxxx9f2"
      client_secret: !SECRETWORKAPP
      alt_auth_method: False
      enable_update: True
      email_sensor:
        - name: Office 365 work Inbox
          max_items: 2
          is_unread: True
          download_attachments: False
      status_sensors: # Cannot be used for personal accounts
        - name: "Office 365 work State"
      todo_sensors:
        enabled: False
```

o365_calendars_Prive.yaml:
```
- cal_id: AQMkADFkMDI0Mm*********************************************JJzQAAAA==
  entities:
    - device_id: Agenda_prive
      end_offset: 24
      name: Agenda Prive
      start_offset: 0
      track: true

- cal_id: AQMkADFkMDI0Mm*********************************************JJzgAAAA==
  entities:
    - device_id: Feestdagen_prive
      end_offset: 24
      name: Feestdagen Prive
      start_offset: 0
      track: false

- cal_id: AQMkADFkMDI0Mm*********************************************JJ0QAAAA==
  entities:
    - device_id: Verjaardagen_prive
      end_offset: 24
      name: Verjaardagen Prive
      start_offset: 0
      track: false
```

o365_calendars_Work.yaml:
```
- cal_id: AQMkADFkMDI0Mm*********************************************JJzQAAAA==
  entities:
  - device_id: Agenda_work
    end_offset: 24
    name: Agenda work
    start_offset: 0
    track: true

- cal_id: AQMkADFkMDI0Mm*********************************************JJzgAAAA==
  entities:
  - device_id: Feestdagen_work
    end_offset: 24
    name: Feestdagen work
    start_offset: 0
    track: false

- cal_id: AQMkADFkMDI0Mm*********************************************JJ0QAAAA==
  entities:
  - device_id: Verjaardagen_work
    end_offset: 24
    name: Verjaardagen work
    start_offset: 0
    track: false
```

(Hope I did not disclose any private or work names/secrets, if so let me know and please respect it.).

### Version information
Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.5
Frontend-versie: 20230802.1 - latest
Office 365 Integration: v4.3.4

### What dit I try already:
1. Restarted the Pi fully.
6. Removed the entities (Setting track to false, restarted, removed the enitity manually) and let it be recreated (Setting track to true, restarted).
7. Re-Authenticated by removing the token cache.
8. Renaming the device_id and enitity names.

### Questions:

- Can I empty the calendars so existing information is re-fetched for the appropriate account (locally stored/cached or whatever)?
- What did I do wrong? (If nothing, is this a bug?)
- How can I avoid this from happening again?

And of course, without saying, thanks for the work and effort in creating this integration and for the upcoming help I hope to find here.
