### ISSUE TITLE
Cannot update description on an existing to do

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/O365-HomeAssistant#190]
if I use an update_item service to try and update the description of a to-do item, it doesn't work ?

Thanks

**Comment by RogerSelwyn** [comment]
I forget is that the todo. service or the o365. service?

**Comment by B-Hartley** [comment]
```
service: todo.update_item
target:
  entity_id: todo.house_jobs_bruce                 
data:
  item: "todo item"
  description: "updated desc"
```
