### ISSUE TITLE
Can I have two sensors query the same folder but for different subjects?

### ISSUE THREAD

**Issue by danielbrunt57** [RogerSelwyn/O365-HomeAssistant#198]
When I configure it this way:
```
      query_sensors:
        - name: "Home Assistant Notifications"
          folder: "Inbox"
          from: "daniel@brunt.ca"
          subject_contains: "Notification from Home Assistant"
          has_attachment: True
          max_items: 5
          is_unread: True
 
        - name: "BC Hydro Step 2"
          folder: "Bills/BC Hydro"
          from: "notifications@bchydro.com"
          subject_contains: "now paying a higher rate"
          max_items: 2
          is_unread: True
 
        - name: "BC Hydro Step 1"
          folder: "Bills/BC Hydro"
          from: "notifications@bchydro.com"
          subject_contains: "bill is ready"
          max_items: 2
          is_unread: True
```
I get an error for the creation of the 2nd BC Hydro sensor:
```
2024-01-04 21:54:34.475 ERROR (MainThread) [homeassistant.components.sensor] Platform o365 does not generate unique IDs. ID AAMkADBjNDgyODcyLTg0YzQtNDM0Yy05OTA1LTE2OGVmNmFhNjkyZgAuAAAAAADWgdR-BEbUTLk7SARdghXOAQCftk0xHnauS4rMoDAPfic9AAAAAV-kAAA=_Daniel already exists - ignoring sensor.bc_hydro_step_2
```
But if I edit the 2nd sensor and change it to another folder then the integration configures it:
```
      query_sensors:
        - name: "Home Assistant Notifications"
          folder: "Inbox"
          from: "daniel@brunt.ca"
          subject_contains: "Notification from Home Assistant"
          has_attachment: True
          max_items: 5
          is_unread: True
 
        - name: "BC Hydro Step 2"
          folder: "Bills/BC Hydro"
          from: "notifications@bchydro.com"
          subject_contains: "now paying a higher rate"
          max_items: 2
          is_unread: True
 
        - name: "BC Hydro Step 1"
          folder: "Bills/Canadian Tire"
          from: "notifications@bchydro.com"
          subject_contains: "bill is ready"
          max_items: 2
          is_unread: True
```
I want to trigger an automation to switch my utility step rates between `Step 1` and `Step 2` when the appropriate email arrives.
Is there any way to have two sensors looking at the same folder?
