### ISSUE TITLE
Shared mailbox help

### ISSUE THREAD

**Issue by Paulwatchful** [RogerSelwyn/O365-HomeAssistant#248]
Many thanks for your work on this great app, I am looking to get the shared mailbox on my account, I can get my emails etc but having an issue with setting up the shared email sensor     

```
o365:
  accounts:
    - account_name: DailyReports 
      client_id: ""
      client_secret: ""
      alt_auth_method: False
      enable_update: False
 email_sensor:
        - name: daily_reports_inbox
          folder: "Inbox"  
          max_items: 20  
          is_unread: False  
          download_attachments: False 
      shared_mailbox: "sharedemail@addresss.com"
```

not sure what I am doing wrong.
