### ISSUE TITLE
Send Email Service not created

### ISSUE THREAD

**Issue by RAW297** [RogerSelwyn/O365-HomeAssistant#252]
Hi,

I have installed and reinstalled a couple of times reading through the documentation and everything seems to be installed and configured correctly and is authenticated.

I can see the integration, it has 3 entities and I can see one action has been created for the **Scan for new calendars**, but I cannot see the **notify.email** action created so that I can send emails via O365.

![365_actions](https://github.com/user-attachments/assets/f9461081-ff6c-4b25-8875-ff5f864d7465)

![0365_actions_2](https://github.com/user-attachments/assets/98a6457b-bfe3-4daa-ae51-5fc6af805bc6)

![365_entities](https://github.com/user-attachments/assets/12ab902f-10bf-4798-9db1-f13c0b3c836b)

![365_permissions](https://github.com/user-attachments/assets/c9095059-9aa0-4f23-af94-a7d5d25da45a)

This is the config I have in the configuration.yaml

```
o365:
  accounts:
    - account_name: Hotmail # Do not use email address or spaces
      client_id: "99xxxxxx-4xxx-442d-xxxx-8axxa46xxxxx"
      client_secret: "Axxxxx~32iv6mxxxxxLP8eiwE_xxxxxxxxYcvm"
      alt_auth_method: False
      enable_update: False
      email_sensor:
        - name: inbox
          max_items: 10
          is_unread: True
          download_attachments: False
      query_sensors:
        - name: "Example"
          folder: "Inbox/Test_Inbox" #Default is Inbox
          from: "mail@example.com"
          subject_contains: "Example subject"
          has_attachment: True
          max_items: 2
          is_unread: True
``` 

Am I missing a step somewhere to get this enabled/configured?

Thanks
