### ISSUE TITLE
Feature Request: count of unread Teams chats

### ISSUE THREAD

**Issue by crlogic** [RogerSelwyn/O365-HomeAssistant#50]
Reading [this commit](https://github.com/O365/python-o365/commit/7f77005c3cee8177d0141e79b8eda8a7b60c5124), my limited understanding is that the base library supports getting Teams messages. Using an "unread_chats" sensor in HA would be really helpful in performing better notifications because work AD policy puts the PC to sleep the moment I make a cup of coffee.

**Comment by crlogic** [comment]
Well I do appreciate you looking and can understand the hesitation of maintaining a project.  If you added replies then everyone would make an HA/Teams bot..  ;)

**Comment by RogerSelwyn** [comment]
OK. I have something that will just show the latest message. Status is the date/time of the message (which is un UTC).

**Comment by crlogic** [comment]
I think that would be useful.  When combined with a button perhaps, any status data/time > last_button_pressed = new message!

**Comment by RogerSelwyn** [comment]
Well I'll let you figure the button bit ;-) I know I could do it in Node Red.

**Comment by RogerSelwyn** [comment]
This is what I have. It will also show a summary or subject if there is one in the chat.
<img width="1139" alt="Screenshot 2022-05-19 at 15 49 58" src="https://user-images.githubusercontent.com/7115783/169325911-122e0dda-2455-4c74-a271-3c889b5f1f84.png">

**Comment by crlogic** [comment]
Awesome, I'll give that a go :)

**Comment by RogerSelwyn** [comment]
See this release which is currently sent to pre-release, so you will need to enable beta releases in HACS.

https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v3.2.0

**Comment by crlogic** [comment]
I removed my existing O365 integration, added v3.2.0, restart core w/ the following config
```
o365:
  accounts:
    - account_name: me
      client_secret: "yadda"
      client_id: "yadda"
      enable_update: True
      status_sensors: # Cannot be used for personal accounts
        - name: "teams_status"
      chat_sensors:
        - name: "teams_chat"
```
I still see the status sensor and it is working. But no sensor.teams_chat.  

Did I do something wrong?  Can investigate later..
