### ISSUE TITLE
Email Sensors are missing

### ISSUE THREAD

**Issue by FaserF** [RogerSelwyn/O365-HomeAssistant#66]
My config: 
```yaml
o365:
  accounts:
    - account_name: 5Freunde
      client_id: !secret O365_client_id
      client_secret: !secret O365_client_secret
      alt_auth_method: False
      enable_update: False
      track_new_calendar: False
      email_sensor:
        - name: inbox
          max_items: 2
          is_unread: True
          download_attachments: False
    - account_name: JUZ
      client_id: !secret O365_client_id
      client_secret: !secret O365_client_secret
      alt_auth_method: False
      enable_update: False
      track_new_calendar: False
      email_sensor:
        - name: inbox
          max_items: 4
          is_unread: True
          download_attachments: False
```

Authentification was successfull, I can also see the token files in ".O365-token-cache" and a "o365_calendars_5Freunde.yaml" and "o365_calendars_JUZ.yaml" were created, despite using "enable_update: False" where I can also see the permissions from Azure.

I have activated debugging loggin, but there is nearly no log input:
```
2022-08-16 10:33:02.362 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration o365 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2022-08-16 10:36:58.413 WARNING (MainThread) [homeassistant.components.sensor] Updating o365 sensor took longer than the scheduled update interval 0:00:30
```

I am seeing no entity at all from the integration, only the conigurator for signing in was there.

**Comment by RogerSelwyn** [comment]
Have you restarted again since authenticating? I forget if it creates the sensor on first start? Is there anything in the o365_calendar yaml files? (enable_update doesn't stop those files being created, it stops update services from being created in HA). Are there no calendar entities? Or are just email ones missing as in your title?

In calendar.py there are three debug statements you can uncomment (remove '# ' from start - note the space after the # must be remove to align the _ below the line above). Then restart. If needed I can provide a version with extra debugging added.

**Comment by FaserF** [comment]
Wow, thanks for the really fast reply. 
Yes there is input in the calendar yaml files:

```
- cal_id: myverylongID
  entities:
    - device_id: Calendar
      end_offset: 24
      name: Calendar
      start_offset: 0
      track: false
```

(Changed it manually to track: false)
There was no calendar entity once left to "track true". Also I have seen in the log that the O365 calendar integration did a scan every 30 seconds.
I did multiple HA restarts and tried playing around with some config options, but nothing changed. 
Is there someting similar in another python file that I should uncomment to give you some more logs? As I have no need for the calendars, but I am interested in the email sensors only.
