### ISSUE TITLE
Is it possible to send emails from a shared mailbox? 

### ISSUE THREAD

**Issue by mydliar** [RogerSelwyn/O365-HomeAssistant#75]
Hi,
Great piece of work, many thanks for this. Just wondering if it's possible to send emails from a shared mailbox (Send as)?
Thanks,

Martin

**Comment by RogerSelwyn** [comment]
I'd have to look at see if that is in the api (which it probably is) and then figure how complex it is.

**Comment by mydliar** [comment]
Thanks, I think I saw it there. No hurry

**Comment by RogerSelwyn** [comment]
Looks like there may be a sender property on the message, so I'll give that a whirl.

**Comment by mydliar** [comment]
Yes, that sounds about right

**Comment by RogerSelwyn** [comment]
Please try this release - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v3.2.3

Structure like this:

```
service: notify.o365_email_primary
data:
  message: The garage door has been open for 10 minutes.
  title: Your Garage Door Friend
  data:
    target: joebloggs@hotmail.com
    sender: mgmt@noname.org.uk
```
