### ISSUE TITLE
"subject: " in tasks

### ISSUE THREAD

**Issue by JinRoh3** [RogerSelwyn/O365-HomeAssistant#96]
<img src="https://user-images.githubusercontent.com/77590503/206743665-9974302d-35c8-40bd-bd54-535abcf881fa.png" width=50%>

I'm currently testing the integration and so far everything worked correctly and the installation was easy, thanks to the detailed documentation.

However, once linked, all my tasks linked from "MS to do" appear with "- Subject: " before the actual task. Would it be possible to get a cleaner name ignoring this?

thanks

**Comment by RogerSelwyn** [comment]
`subject` is the attribute name in the array of `all_tasks`. Each item in the array is denoted by the hyphen. You are able to iterate through the array. If you had set a reminder or a due date these would also show as attributes of the item.

```
all_tasks: 
- subject: Pick up the mail
  due: '2023-01-01'
  reminder: '2023-01-01T07:00:00+00:00'
- subject: Pick up the mail
  due: '2023-01-01'
  reminder: '2023-01-01T12:00:00+00:00'
```
